name: Scaffold

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch only

jobs:
  scaffold:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Scaffold
        uses: github/scaffold@v3  # Updated version
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
